language: java
sudo: false
dist: trusty

matrix:
  include:
    - jdk: oraclejdk7
    - jdk: oraclejdk8
    - jdk: oraclejdk9 # JDK 9-ea+174 provided by Travis will be replaced by 9+177 in "before_install"
      before_install:
        - cd ~
        - wget http://download.java.net/java/jdk9/archive/177/binaries/jdk-9+177_linux-x64_bin.tar.gz
        - tar -xzf jdk-9+177_linux-x64_bin.tar.gz
        - export JAVA_HOME=~/jdk-9
        - PATH=$JAVA_HOME/bin:$PATH
        - cd -
